packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: 19.0.0
  react-dom: 19.0.0
  react-native: 0.79.2
  react-native-web: 0.20.0
  typescript: 5.9.3
  vitest: 3.2.6
  tsx: 4.20.3
  zod: 3.24.4
  "@types/react": 19.0.14
  "@vitejs/plugin-react": 4.7.0
